services:
  - type: web
    name: ai-fashion-backend
    env: python
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: python start.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: ENVIRONMENT
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_OUMg09DpBurh@ep-rough-thunder-adqlho94-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: PYTHON_VERSION
        value: 3.11.9
    autoDeploy: true
    branch: main
    repo: https://github.com/TaddsTechnology/Ai-Fashion.git
